version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:15"
      timezone: "Asia/Jerusalem"
    open-pull-requests-limit: 10
    labels: ["deps", "python"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
